BEGIN TRANSACTION;
DROP TABLE IF EXISTS "SUPPLIER";
CREATE TABLE IF NOT EXISTS "SUPPLIER" (
	"supplier_id"	INTEGER NOT NULL,
	"supplier_name"	TEXT NOT NULL,
	"address"	TEXT NOT NULL,
	"email"	TEXT NOT NULL,
	PRIMARY KEY("supplier_id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "PRODUCT";
CREATE TABLE IF NOT EXISTS "PRODUCT" (
	"product_id"	INTEGER NOT NULL,
	"supplier_id"	INTEGER NOT NULL,
	"product_name"	TEXT NOT NULL,
	"retail_price"	INTEGER NOT NULL,
	"stock_level"	INTEGER NOT NULL,
	"product_code"	INTEGER NOT NULL,
	"supplier_price"	REAL NOT NULL,
	PRIMARY KEY("product_id" AUTOINCREMENT),
	FOREIGN KEY("supplier_id") REFERENCES "SUPPLIER"("supplier_id") ON DELETE CASCADE
);
DROP TABLE IF EXISTS "CUSTOMER";
CREATE TABLE IF NOT EXISTS "CUSTOMER" (
	"customer_id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL,
	"shipping_address"	TEXT NOT NULL,
	"email"	TEXT NOT NULL,
	PRIMARY KEY("customer_id")
);
DROP TABLE IF EXISTS "SHOPPING_ORDER";
CREATE TABLE IF NOT EXISTS "SHOPPING_ORDER" (
	"order_id"	INTEGER NOT NULL,
	"status"	TEXT NOT NULL,
	"date_sent"	TEXT,
	"date_delivered"	TEXT,
	"customer_id"	INTEGER NOT NULL,
	FOREIGN KEY("customer_id") REFERENCES "CUSTOMER"("customer_id"),
	PRIMARY KEY("order_id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "PRODUCT_ORDER";
CREATE TABLE IF NOT EXISTS "PRODUCT_ORDER" (
	"product_id"	INTEGER NOT NULL,
	"order_id"	INTEGER NOT NULL,
	"quantity"	INTEGER NOT NULL,
	FOREIGN KEY("product_id") REFERENCES "PRODUCT"("product_id"),
	FOREIGN KEY("order_id") REFERENCES "SHOPPING_ORDER"("order_id")
);
COMMIT;